name: CD

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create .env
      run: |
        touch .env
        echo REACT_APP_NAME="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
        echo REACT_APP_GOOGLE_OAUTH_CLIENT_ID=${{ secrets.API_KEY }} >> .env
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        pull: true
        push: true
        cache-from: type=registry,ref=${{ secrets.DOCKER_REPO }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'staging' }}
        cache-to: type=inline
        tags: ${{ secrets.DOCKER_REPO }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'staging' }}
